sudo: false
language: node_js
node_js:
- 6
before_install:
- npm install @dojo/cli grunt-cli typings -g


env:

script: 

jobs:
  include:
    stage: Test site
    env:
      - TUTORIAL=N/A
    script:
      - grunt test
      - grunt ci
deploy:
  provider: script
  script: grunt publish
  skip_cleanup: true
  on:
    branch: master
