sudo: false
language: node_js
node_js:
- 6
before_install:
- npm install @dojo/cli grunt-cli typings -g


script: 

jobs:


deploy:
  provider: script
  script: grunt publish
  skip_cleanup: true
  on:
    branch: master
